### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by bluemix** [gunterhager/UDPBroadcastConnection#1]
Hello dear @gunterhager,
are there any updates soon for supporting Swift 3?
thanks.

**Comment by gunterhager** [comment]
I converted the code to Swift 3 already. I still need to test it which i hope i can do in the next days.

**Comment by bluemix** [comment]
ok, thanks a lot 👍

**Comment by gunterhager** [comment]
Fixed by version 2.0
