### ISSUE TITLE
Error "Can't assign requested address"

### ISSUE THREAD

**Issue by Ricardo1980** [gunterhager/UDPBroadcastConnection#10]
Hello,

Sometimes I receive this error:
"UDP connection failed to send data: Can't assign requested address"
I think it is because I am changing to a different wifi network while I send packets. Is it related?

Maybe I have to recreate the socket when I see that kind of error.

Thanks.

**Comment by gunterhager** [comment]
When this error happens, the socket is closed automatically. So you should just send the message again. This will open a new socket, too.
Unfortunately I didn't implement any error handling support when sending messages via `sendBroadcast()`. I think the function should throw when an error occurs.

**Comment by gunterhager** [comment]
Next version of UDPBroadcastConnection will allow to handle errors.
