### ISSUE TITLE
Program receive same sent packets

### ISSUE THREAD

**Issue by eugeniobaglieri** [gunterhager/UDPBroadcastConnection#13]
I'm connected to a device specific wifi (something like arduino)
I'm sending data packet, and I should receive as response from the device the packet id.
The packet I'm sending is 6byte long, the response packet is 1 byte long.
In the Xcode console log I noted something strange:

```
"UDP connection sent 6 bytes" <--- This is ok
()
"UDP connection received 6 bytes from 10.10.10.110:4150" <--- WTF?
"UDP connection received 1 bytes from 10.10.10.10:4150" <--- This is ok
```

10.10.10.10 is the "remote" device,
10.10.10.110 is my computer/iphone inside its network.

Why am I receiving 6 byte also from localhost?

**Comment by gunterhager** [comment]
That's interesting, i never had this behaviour during my tests. It seems like you receive your own broadcast message, too.

**Comment by eugeniobaglieri** [comment]
it was caused by
```
UDPBroadcastConnection(port: Config.port, bindIt: true, handler: {...})
```

putting the bindIt parameter to false, resolved the problem
