### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by TahaMalas** [gunterhager/UDPBroadcastConnection#14]
This is my implementation of the class you created.

```
let broadcastConnection = UDPBroadcastConnection(port: 15600, handler: nil)
        let data = Data(base64Encoded: "5555 1234", options: Data.Base64DecodingOptions.ignoreUnknownCharacters)
        
        broadcastConnection.sendBroadcast(data!)
        
```

But I'm getting an error in the terminal 
```
"UDP connection failed to send data: Can\'t assign requested address"
"Closing UDP socket"
```

How can I solve it?

**Comment by gunterhager** [comment]
Did you try to send a UDP broadcast over cellular network? I get the same error when i disable WIFI. UDP broadcast is only allowed on local networks AFAIK. Even then some gateways or router may block UDP broadcast, especially when doing it often during testing, so proceed with care.

**Comment by TahaMalas** [comment]
Thanks it worked perfectly, But the handler is not being invoked at all! even when a successful request has been sent and received! Do you know why is that it put bindIt to true but still closing the connection as soon as the request has been sent, is there a way to wait for the IP Address of the receiving part?

**Comment by gunterhager** [comment]
I've added example code and a new Python script to test sending and receiving. It works fine for me. Please try it out.

**Comment by TahaMalas** [comment]
I've tried the new code you pushed, still nothing happens! .. I'm trying to get the IP address of a windows application that receives my UDP broadcast I think the windows application doesn't respond with anything but it receives the datagram packet I sent, so does the handler get invoked once a device on my local machine send a UDP datagram to me or when someone receives it? Thanks for your patience.

**Comment by gunterhager** [comment]
Sorry for the late answer: when you send out a broadcast message and someone receives it but doesn't answer, then there's no way your app will know about the receiving part. So your Windows app needs to send some UDP datagram to you. Only then the handler will be called.

**Comment by TahaMalas** [comment]
Never mind thank you for your great effort
