### ISSUE TITLE
Is there a command to 'dispose' of the connection quickly?

### ISSUE THREAD

**Issue by JohnRMilner** [gunterhager/UDPBroadcastConnection#15]
It seems to me that the instance of UDPBroadcast connection takes some time to be disposed of.  I'm using the framework to broadcast a UDP OSC message to an XR18 console.  The console replies with its IP address, and other information.  This is all working fine.  The problem is when I disable WiFi, send the command, re-enable WiFi, send the command again, the socket still seems to be tied up with the previous 'No WiFi' attempt.  I've tried to dispose of the 'old' connection like this:`broadcastConnection.closeConnection(true)
            broadcastConnection = nil` and then creating another: `broadcastConnection = UDPBroadcastConnection(port: Config.Ports.broadcast) {  (ipAddress: String, port: Int, response: [UInt8]) -> Void in
            let log = "Received from \(ipAddress):\(port):\n\n\(response)"
            print(log)
        }`

Even though WiFi is connected, and all is as it should be, the returned result is still nil, until I close the viewController, or wait for around 90 seconds.  Is there a better way to approach this?  Any help would be much appreciated!

**Comment by gunterhager** [comment]
I think this behaviour could result from using `broadcastConnection.closeConnection(true)`. The syntax here is quite misleading, `true` specifies that the connection should be reopened. Try using `false`. I didn't test the setup you're describing, so this is just speculation.

For better error handling please try the new 3.0 version, maybe you can find out what's going on.

**Comment by JohnRMilner** [comment]
Thanks for the quick reply!  Will try these things, and get back to you!

**Comment by JohnRMilner** [comment]
Gunter

Re below, I haven’t really got any further with this - it seems that the socket ‘hangs around’ for up to a minute, even though it has supposedly been disposed of.  Ah well!

On another topic, do you have any information about compiling your framework as Universal, so that it includes i386 and x86_64 targets all in the same framework package?  It would be great to be able to compile Apps in the simulator without having to switch frameworks…

I have read that you can use -lipo to do this, but any information would be much appreciated!

Thanks for a great framework!

Best Regards

John Milner
