### ISSUE TITLE
Archive installation failed using the Carthage

### ISSUE THREAD

**Issue by osfunapps** [gunterhager/UDPBroadcastConnection#19]
Hi,

got an error when running cert update:

error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'UDPBroadcast macOS')

any way to resolve this?

Thanks

**Comment by gunterhager** [comment]
Thanks for reporting this. It seems there was a source file missing from macOS, tvOS and watchOS targets. Should be fixed in the new version.
