### ISSUE TITLE
Unicast also?

### ISSUE THREAD

**Issue by snovak** [gunterhager/UDPBroadcastConnection#21]
Hi Gunter, 

I'm using your UDPBroadcastConnection to stream messages at 30-60 messages per second, but notice a performance impact on certain networks.  Is it possible to switch from broadcast to unicast after I've found my client IP?  Do you think that would improve my performance issue?   

Sorry, I posted this request for advice as an issue, it is not an issue.  Didn't know where else to ask. 

Thank you!

**Comment by gunterhager** [comment]
It's generally not the best idea to communicate too much using broadcast. Once you found your client you definitely go unicast.

**Comment by snovak** [comment]
Sorry if this is a naive question,  Is there a way to switch your lib from broadcast to unicast?  Or simply use something different?  Any recommendations?

**Comment by gunterhager** [comment]
My library only supports broadcast messages - sorry no unicast. 
But I think it should be pretty straightforward to take my `createSocket()` function and use the client IP address instead of the broadcast address.
