### ISSUE TITLE
Is there a way to receive udp data from a remote udp server?

### ISSUE THREAD

**Issue by ghost** [gunterhager/UDPBroadcastConnection#22]
Hey,

i am looking for  a simple way to receive udp data from a remote udp server im my LAN. I tried to modify this project to get it working with another IP Address targeting my broadcast connection, but unfortunately I failed.

Did you ever thought about it?

**Comment by gunterhager** [comment]
I really used it only for broadcasting to be able to find devices on a LAN (similar to UPNP or Bonjour). I don't use UDP data communication and have no plans to do so currently. I'm sorry that I can't help you there.
