### ISSUE TITLE
Send Data?

### ISSUE THREAD

**Issue by AMAsskicker** [gunterhager/UDPBroadcastConnection#3]
hello @gunterhager, 
What are the chances you could post rewritten code to send 8-bit hex data instead of a string?

**Comment by gunterhager** [comment]
Sorry, i was on vacation away from my computer 😁
Sounds like a valid use case, unfortunately my time is pretty limited currently. I can't promise anything, but i'll look into it.

**Comment by AMAsskicker** [comment]
Sounds good. Hope your vacation was good.

**Comment by gunterhager** [comment]
I rewrote the framework to allow  sending `Data` like:

```
guard let data = message.data(using: .utf8) else { return }
sendBroadcast(data)
```
