### ISSUE TITLE
Set IP

### ISSUE THREAD

**Issue by J-Arji** [gunterhager/UDPBroadcastConnection#5]
hi how can set ip to this library
thanks

**Comment by gunterhager** [comment]
I'm sorry, but i don't think i understand your question. Why would you want to set an IP address? This framework is used to send a UDP broadcast message. Broadcasts are sent to a special IP address that's fixed for all networks.

**Comment by Depicus** [comment]
If you want to sent to another address, for example SSDP then add

`inet_aton("239.255.255.250", &address.sin_addr)`

at line 50 where the initialisation takes place

**Comment by Phoenix7351** [comment]
Depicus's comment did not work for me. I'm trying to broadcast an SSDP message--actually to the exact IP in his comment, so I imagine this isn't a crazy thing to do. I've tried all kinds of things using different frameworks, but I can't for the life of me get my phone to broadcast to that IP--at least not in a way that I can see it in Wireshark.
